### ISSUE TITLE
Develop Index.html- hero section.

### ISSUE THREAD

**Issue by jhonatanrojasbastidas** [rtsc8/hostal_donde_las_paisas#12]
im working on  footer section but the hero section disable my footer section. i can not see with hero es able; that is a problem or a error or is a problem with my footer section.

**Comment by jusk02** [comment]
Hi @jhonatanrojasbastidas , i have just checked develop and the layout seems to flow as expected, please review and if its fixed close this issue, if not add instructions on how to replicate your issue.
